### ISSUE TITLE
Recover Regression Information

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/tregression#9]
As mentioned in title.

**Comment by llmhyy** [comment]
hi @lylytran 

I got the following exception when I store a regression. Would you please kindly have a check tomorrow?

java.sql.BatchUpdateException: Field 'location_id' doesn't have a default value
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
	at microbat.sql.TraceRecorder.insertLocation(TraceRecorder.java:149)
	at microbat.sql.TraceRecorder.insertSteps(TraceRecorder.java:72)
	at microbat.sql.TraceRecorder.insertTrace(TraceRecorder.java:62)
	at tregression.io.RegressionRecorder.record(RegressionRecorder.java:42)
	at tregression.empiricalstudy.TrialGenerator.analyzeTestCase(TrialGenerator.java:281)
	at tregression.empiricalstudy.TrialGenerator.generateTrials(TrialGenerator.java:67)
	at tregression.handler.SeparateVersionHandler$1.run(SeparateVersionHandler.java:41)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Field 'location_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
	... 10 more
java.sql.BatchUpdateException: Field 'location_id' doesn't have a default value
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
	at microbat.sql.TraceRecorder.insertLocation(TraceRecorder.java:149)
	at microbat.sql.TraceRecorder.insertSteps(TraceRecorder.java:72)
	at microbat.sql.TraceRecorder.insertTrace(TraceRecorder.java:62)
	at tregression.io.RegressionRecorder.record(RegressionRecorder.java:42)
	at tregression.empiricalstudy.TrialGenerator.analyzeTestCase(TrialGenerator.java:281)
	at tregression.empiricalstudy.TrialGenerator.generateTrials(TrialGenerator.java:67)
	at tregression.handler.SeparateVersionHandler$1.run(SeparateVersionHandler.java:41)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Field 'location_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
	... 10 more

**Comment by llmhyy** [comment]
done
